[project]
name = 'Decentralized-Biotechnology-Access-and-Innovation-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.personalized-medicine-equity]
path = 'contracts/personalized-medicine-equity.clar'
clarity_version = 2
epoch = 2.5

[contracts.pharma-patent-reform]
path = 'contracts/pharma-patent-reform.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
